[{"name": "test.test_detect_ranges.DetectRanges.test_first", "status": "failed", "message": "Lists differ: [2, 4, 5, 6, 7, 8, 10, 12, 13] != [2, (4, 9), 10, (12, 14)]\n\nFirst differing element 1:\n4\n(4, 9)\n\nFirst list contains 5 additional elements.\nFirst extra element 4:\n7\n\n- [2, 4, 5, 6, 7, 8, 10, 12, 13]\n+ [2, (4, 9), 10, (12, 14)] : Incorrect result for the input list [2, 5, 4, 8, 12, 6, 7, 10, 13]!", "passed": false, "points": ["p01-10.1"], "backtrace": ["  File \"/home/jukka/anaconda3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home/jukka/anaconda3/lib/python3.7/unittest/case.py\", line 615, in run\n    testMethod()\n", "  File \"/home/jukka/projects/python/data-analysis/hy-data-analysis-with-python-summer-2019/part01-e10_detect_ranges/test/test_detect_ranges.py\", line 23, in test_first\n    self.assertEqual(result, [2, (4, 9), 10, (12, 14)], msg=\"Incorrect result for the input list %s!\" % L)\n", "  File \"/home/jukka/anaconda3/lib/python3.7/unittest/case.py\", line 839, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/home/jukka/anaconda3/lib/python3.7/unittest/case.py\", line 1045, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type=list)\n", "  File \"/home/jukka/anaconda3/lib/python3.7/unittest/case.py\", line 1027, in assertSequenceEqual\n    self.fail(msg)\n", "  File \"/home/jukka/anaconda3/lib/python3.7/unittest/case.py\", line 680, in fail\n    raise self.failureException(msg)\n"]}, {"name": "test.test_detect_ranges.DetectRanges.test_random", "status": "failed", "message": "10 != 187 : Wrong result for input list [-32, 96, 5, -18, 48, 25, 91, 92, -99, -34]!", "passed": false, "points": ["p01-10.1"], "backtrace": ["  File \"/home/jukka/anaconda3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home/jukka/anaconda3/lib/python3.7/unittest/case.py\", line 615, in run\n    testMethod()\n", "  File \"/home/jukka/projects/python/data-analysis/hy-data-analysis-with-python-summer-2019/part01-e10_detect_ranges/test/test_detect_ranges.py\", line 41, in test_random\n    self.assertEqual(len(result), len(complement_result)+1, msg=\"Wrong result for input list %s!\" % L)\n", "  File \"/home/jukka/anaconda3/lib/python3.7/unittest/case.py\", line 839, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/home/jukka/anaconda3/lib/python3.7/unittest/case.py\", line 832, in _baseAssertEqual\n    raise self.failureException(msg)\n"]}]